<?php
/**
 * SOFIR Elementor Template Library
 * Professional templates inspired by Slider Revolution
 */

return [
    'popup'   => [
        [
            'id'          => 'newsletter-popup',
            'title'       => \__( 'Newsletter Subscription', 'sofir' ),
            'description' => \__( 'Elegant newsletter popup with email subscription form', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/newsletter-popup.jpg',
            'type'        => 'popup',
            'pro'         => false,
            'tags'        => [ 'marketing', 'email', 'subscription' ],
        ],
        [
            'id'          => 'promo-popup',
            'title'       => \__( 'Promotional Offer', 'sofir' ),
            'description' => \__( 'Eye-catching promotional popup with countdown timer', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/promo-popup.jpg',
            'type'        => 'popup',
            'pro'         => false,
            'tags'        => [ 'sale', 'discount', 'promotion' ],
        ],
        [
            'id'          => 'exit-intent-popup',
            'title'       => \__( 'Exit Intent Offer', 'sofir' ),
            'description' => \__( 'Special offer popup triggered on exit intent', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/exit-intent-popup.jpg',
            'type'        => 'popup',
            'pro'         => false,
            'tags'        => [ 'conversion', 'exit-intent', 'offer' ],
        ],
        [
            'id'          => 'video-popup',
            'title'       => \__( 'Video Presentation', 'sofir' ),
            'description' => \__( 'Full-screen video popup with modern design', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/video-popup.jpg',
            'type'        => 'popup',
            'pro'         => false,
            'tags'        => [ 'video', 'media', 'presentation' ],
        ],
        [
            'id'          => 'announcement-popup',
            'title'       => \__( 'Announcement Banner', 'sofir' ),
            'description' => \__( 'Important announcement popup with call-to-action', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/announcement-popup.jpg',
            'type'        => 'popup',
            'pro'         => false,
            'tags'        => [ 'announcement', 'news', 'update' ],
        ],
        [
            'id'          => 'contact-popup',
            'title'       => \__( 'Quick Contact Form', 'sofir' ),
            'description' => \__( 'Compact contact form popup for quick inquiries', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/contact-popup.jpg',
            'type'        => 'popup',
            'pro'         => false,
            'tags'        => [ 'contact', 'form', 'inquiry' ],
        ],
    ],

    'card'    => [
        [
            'id'          => 'post-card-modern',
            'title'       => \__( 'Modern Post Card', 'sofir' ),
            'description' => \__( 'Clean and modern blog post card with hover effects', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/post-card-modern.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'blog', 'post', 'article' ],
        ],
        [
            'id'          => 'product-card-premium',
            'title'       => \__( 'Premium Product Card', 'sofir' ),
            'description' => \__( 'Elegant product card with price and add to cart button', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/product-card-premium.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'product', 'ecommerce', 'shop' ],
        ],
        [
            'id'          => 'team-member-card',
            'title'       => \__( 'Team Member Card', 'sofir' ),
            'description' => \__( 'Professional team member card with social links', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/team-member-card.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'team', 'staff', 'profile' ],
        ],
        [
            'id'          => 'service-card-minimal',
            'title'       => \__( 'Minimal Service Card', 'sofir' ),
            'description' => \__( 'Clean minimal card for showcasing services', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/service-card-minimal.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'service', 'feature', 'business' ],
        ],
        [
            'id'          => 'pricing-card-creative',
            'title'       => \__( 'Creative Pricing Card', 'sofir' ),
            'description' => \__( 'Eye-catching pricing card with features list', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/pricing-card-creative.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'pricing', 'plan', 'subscription' ],
        ],
        [
            'id'          => 'testimonial-card',
            'title'       => \__( 'Testimonial Card', 'sofir' ),
            'description' => \__( 'Beautiful testimonial card with client info', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/testimonial-card.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'testimonial', 'review', 'feedback' ],
        ],
        [
            'id'          => 'event-card',
            'title'       => \__( 'Event Card', 'sofir' ),
            'description' => \__( 'Modern event card with date, time, and location', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/event-card.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'event', 'calendar', 'schedule' ],
        ],
        [
            'id'          => 'portfolio-card',
            'title'       => \__( 'Portfolio Card', 'sofir' ),
            'description' => \__( 'Creative portfolio card with overlay effects', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/portfolio-card.jpg',
            'type'        => 'card',
            'pro'         => false,
            'tags'        => [ 'portfolio', 'gallery', 'project' ],
        ],
    ],

    'page'    => [
        [
            'id'          => 'hero-slider-page',
            'title'       => \__( 'Hero Slider Landing', 'sofir' ),
            'description' => \__( 'Full-screen hero slider with call-to-action buttons', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/hero-slider-page.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'landing', 'hero', 'slider' ],
        ],
        [
            'id'          => 'about-company-page',
            'title'       => \__( 'About Company', 'sofir' ),
            'description' => \__( 'Professional about page with team and timeline', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/about-company-page.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'about', 'company', 'team' ],
        ],
        [
            'id'          => 'services-showcase',
            'title'       => \__( 'Services Showcase', 'sofir' ),
            'description' => \__( 'Modern services page with icon boxes and features', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/services-showcase.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'services', 'features', 'business' ],
        ],
        [
            'id'          => 'contact-page-modern',
            'title'       => \__( 'Modern Contact Page', 'sofir' ),
            'description' => \__( 'Contact page with map, form, and contact info', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/contact-page-modern.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'contact', 'form', 'map' ],
        ],
        [
            'id'          => 'portfolio-gallery-page',
            'title'       => \__( 'Portfolio Gallery', 'sofir' ),
            'description' => \__( 'Masonry portfolio gallery with filters', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/portfolio-gallery-page.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'portfolio', 'gallery', 'work' ],
        ],
        [
            'id'          => 'pricing-plans-page',
            'title'       => \__( 'Pricing Plans', 'sofir' ),
            'description' => \__( 'Attractive pricing page with comparison table', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/pricing-plans-page.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'pricing', 'plans', 'comparison' ],
        ],
        [
            'id'          => 'faq-page',
            'title'       => \__( 'FAQ Page', 'sofir' ),
            'description' => \__( 'Frequently asked questions with accordion layout', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/faq-page.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'faq', 'help', 'support' ],
        ],
        [
            'id'          => 'coming-soon-page',
            'title'       => \__( 'Coming Soon', 'sofir' ),
            'description' => \__( 'Beautiful coming soon page with countdown', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/coming-soon-page.jpg',
            'type'        => 'page',
            'pro'         => false,
            'tags'        => [ 'coming-soon', 'launch', 'countdown' ],
        ],
    ],

    'post'    => [
        [
            'id'          => 'single-post-modern',
            'title'       => \__( 'Modern Single Post', 'sofir' ),
            'description' => \__( 'Clean single post layout with author box and related posts', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/single-post-modern.jpg',
            'type'        => 'single-post',
            'pro'         => false,
            'tags'        => [ 'blog', 'post', 'article' ],
        ],
        [
            'id'          => 'single-post-magazine',
            'title'       => \__( 'Magazine Style Post', 'sofir' ),
            'description' => \__( 'Magazine-style single post with featured image', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/single-post-magazine.jpg',
            'type'        => 'single-post',
            'pro'         => false,
            'tags'        => [ 'magazine', 'blog', 'editorial' ],
        ],
        [
            'id'          => 'single-product-layout',
            'title'       => \__( 'Product Single Layout', 'sofir' ),
            'description' => \__( 'Complete product page with gallery and tabs', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/single-product-layout.jpg',
            'type'        => 'single-product',
            'pro'         => false,
            'tags'        => [ 'product', 'woocommerce', 'shop' ],
        ],
        [
            'id'          => 'single-portfolio-item',
            'title'       => \__( 'Portfolio Item', 'sofir' ),
            'description' => \__( 'Portfolio single item with image gallery', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/single-portfolio-item.jpg',
            'type'        => 'single',
            'pro'         => false,
            'tags'        => [ 'portfolio', 'project', 'case-study' ],
        ],
    ],

    'archive' => [
        [
            'id'          => 'blog-archive-grid',
            'title'       => \__( 'Blog Archive Grid', 'sofir' ),
            'description' => \__( 'Grid layout blog archive with sidebar', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/blog-archive-grid.jpg',
            'type'        => 'archive',
            'pro'         => false,
            'tags'        => [ 'blog', 'archive', 'grid' ],
        ],
        [
            'id'          => 'blog-archive-masonry',
            'title'       => \__( 'Blog Archive Masonry', 'sofir' ),
            'description' => \__( 'Masonry layout blog archive with filters', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/blog-archive-masonry.jpg',
            'type'        => 'archive',
            'pro'         => false,
            'tags'        => [ 'blog', 'masonry', 'filter' ],
        ],
        [
            'id'          => 'shop-archive',
            'title'       => \__( 'Shop Archive', 'sofir' ),
            'description' => \__( 'WooCommerce shop archive with filters and sorting', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/shop-archive.jpg',
            'type'        => 'archive',
            'pro'         => false,
            'tags'        => [ 'shop', 'products', 'woocommerce' ],
        ],
        [
            'id'          => 'portfolio-archive',
            'title'       => \__( 'Portfolio Archive', 'sofir' ),
            'description' => \__( 'Portfolio archive with category filtering', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/portfolio-archive.jpg',
            'type'        => 'archive',
            'pro'         => false,
            'tags'        => [ 'portfolio', 'archive', 'gallery' ],
        ],
        [
            'id'          => 'listing-archive',
            'title'       => \__( 'Directory Listing Archive', 'sofir' ),
            'description' => \__( 'Directory listings with map and filters', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/listing-archive.jpg',
            'type'        => 'archive',
            'pro'         => false,
            'tags'        => [ 'directory', 'listing', 'map' ],
        ],
    ],

    'header'  => [
        [
            'id'          => 'header-transparent',
            'title'       => \__( 'Transparent Header', 'sofir' ),
            'description' => \__( 'Modern transparent header with sticky navigation', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/header-transparent.jpg',
            'type'        => 'header',
            'pro'         => false,
            'tags'        => [ 'header', 'navigation', 'menu' ],
        ],
        [
            'id'          => 'header-with-topbar',
            'title'       => \__( 'Header with Top Bar', 'sofir' ),
            'description' => \__( 'Header with top bar for contact info', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/header-with-topbar.jpg',
            'type'        => 'header',
            'pro'         => false,
            'tags'        => [ 'header', 'topbar', 'contact' ],
        ],
        [
            'id'          => 'header-centered',
            'title'       => \__( 'Centered Header', 'sofir' ),
            'description' => \__( 'Elegant centered header with logo', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/header-centered.jpg',
            'type'        => 'header',
            'pro'         => false,
            'tags'        => [ 'header', 'centered', 'elegant' ],
        ],
    ],

    'footer'  => [
        [
            'id'          => 'footer-4-columns',
            'title'       => \__( 'Footer 4 Columns', 'sofir' ),
            'description' => \__( 'Footer with 4 columns and newsletter subscription', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/footer-4-columns.jpg',
            'type'        => 'footer',
            'pro'         => false,
            'tags'        => [ 'footer', 'columns', 'newsletter' ],
        ],
        [
            'id'          => 'footer-minimal',
            'title'       => \__( 'Minimal Footer', 'sofir' ),
            'description' => \__( 'Clean minimal footer with social links', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/footer-minimal.jpg',
            'type'        => 'footer',
            'pro'         => false,
            'tags'        => [ 'footer', 'minimal', 'social' ],
        ],
        [
            'id'          => 'footer-cta',
            'title'       => \__( 'Footer with CTA', 'sofir' ),
            'description' => \__( 'Footer with prominent call-to-action section', 'sofir' ),
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/elementor-templates/footer-cta.jpg',
            'type'        => 'footer',
            'pro'         => false,
            'tags'        => [ 'footer', 'cta', 'action' ],
        ],
    ],
];
