<?php
return [
    'landing'   => [
        [
            'slug'        => 'startup-launch',
            'title'       => \__( 'Startup Launch', 'sofir' ),
            'description' => \__( 'Hero besar dengan CTA, daftar fitur, testimoni, dan pricing table.', 'sofir' ),
            'path'        => __DIR__ . '/landing/startup-launch.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/startup-launch.svg',
            'category'    => 'landing',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [ 'testimonial', 'pricing' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'agency-spotlight',
            'title'       => \__( 'Agency Spotlight', 'sofir' ),
            'description' => \__( 'Layout elegan untuk agensi dengan layanan, proses kerja, dan form kontak.', 'sofir' ),
            'path'        => __DIR__ . '/landing/agency-spotlight.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/agency-spotlight.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'service' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'restaurant-menu',
            'title'       => \__( 'Restaurant Menu', 'sofir' ),
            'description' => \__( 'Tampilan menu restoran dengan gambar makanan, harga, dan booking form.', 'sofir' ),
            'path'        => __DIR__ . '/landing/restaurant-menu.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/restaurant-menu.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'menu_item' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'real-estate-property',
            'title'       => \__( 'Real Estate Property', 'sofir' ),
            'description' => \__( 'Landing page properti dengan gallery, spesifikasi, dan contact agent.', 'sofir' ),
            'path'        => __DIR__ . '/landing/real-estate-property.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/real-estate-property.svg',
            'category'    => 'landing',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [ 'property' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'event-registration',
            'title'       => \__( 'Event Registration', 'sofir' ),
            'description' => \__( 'Landing page acara dengan countdown, speaker list, dan ticket pricing.', 'sofir' ),
            'path'        => __DIR__ . '/landing/event-registration.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/event-registration.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'pricing' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'course-landing',
            'title'       => \__( 'Course Landing', 'sofir' ),
            'description' => \__( 'Landing page kursus online dengan curriculum, testimonials, dan progress bars.', 'sofir' ),
            'path'        => __DIR__ . '/landing/course-landing.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/course-landing.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'faq', 'testimonial' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'saas-product',
            'title'       => \__( 'SaaS Product', 'sofir' ),
            'description' => \__( 'Landing page SaaS dengan features, pricing table, dan FAQs.', 'sofir' ),
            'path'        => __DIR__ . '/landing/saas-product.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/saas-product.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'pricing', 'faq' ],
            'theme'       => 'block-theme',
        ],
    ],
    'directory' => [
        [
            'slug'        => 'city-directory',
            'title'       => \__( 'City Directory', 'sofir' ),
            'description' => \__( 'Listing grid dengan filter lokasi, rating, dan kategori.', 'sofir' ),
            'path'        => __DIR__ . '/directory/city-directory.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/city-directory.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'directory_listing' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'healthcare-network',
            'title'       => \__( 'Healthcare Network', 'sofir' ),
            'description' => \__( 'Direktori dokter dengan pencarian cepat dan highlight layanan.', 'sofir' ),
            'path'        => __DIR__ . '/directory/healthcare-network.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/healthcare-network.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'doctor', 'service' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'fitness-studio-directory',
            'title'       => \__( 'Fitness Studio Directory', 'sofir' ),
            'description' => \__( 'Direktori gym dan studio fitness dengan rating, jadwal, dan booking.', 'sofir' ),
            'path'        => __DIR__ . '/directory/fitness-studio-directory.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/fitness-studio-directory.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'fitness_studio' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'hotel-booking',
            'title'       => \__( 'Hotel Booking', 'sofir' ),
            'description' => \__( 'Direktori hotel dengan search, filter, dan map integration.', 'sofir' ),
            'path'        => __DIR__ . '/directory/hotel-booking.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/hotel-booking.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'hotel' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'job-board',
            'title'       => \__( 'Job Board', 'sofir' ),
            'description' => \__( 'Job listing board dengan filter, categories, dan company profiles.', 'sofir' ),
            'path'        => __DIR__ . '/directory/job-board.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/job-board.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'job' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'lawyer-directory',
            'title'       => \__( 'Lawyer Directory', 'sofir' ),
            'description' => \__( 'Direktori pengacara dengan practice areas, reviews, dan contact form.', 'sofir' ),
            'path'        => __DIR__ . '/directory/lawyer-directory.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/lawyer-directory.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'lawyer', 'testimonial' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'web-directory-dashboard',
            'title'       => \__( 'Web Directory Dashboard', 'sofir' ),
            'description' => \__( 'Dashboard komprehensif untuk mengelola web directory dengan statistik, map interaktif, filter, dan analytics.', 'sofir' ),
            'path'        => __DIR__ . '/directory/web-directory-dashboard.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/web-directory-dashboard.svg',
            'category'    => 'directory',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [ 'listing' ],
            'theme'       => 'block-theme',
        ],
    ],
    'blog'      => [
        [
            'slug'        => 'modern-magazine',
            'title'       => \__( 'Modern Magazine', 'sofir' ),
            'description' => \__( 'Portal berita dengan layout hero carousel, kategori, dan highlight editorial.', 'sofir' ),
            'path'        => __DIR__ . '/blog/modern-magazine.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/modern-magazine.svg',
            'category'    => 'blog',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'tech-news-portal',
            'title'       => \__( 'Tech News Portal', 'sofir' ),
            'description' => \__( 'Portal berita teknologi dengan trending sidebar dan latest stories grid.', 'sofir' ),
            'path'        => __DIR__ . '/blog/tech-news-portal.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/tech-news-portal.svg',
            'category'    => 'blog',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'personal-blog',
            'title'       => \__( 'Personal Blog', 'sofir' ),
            'description' => \__( 'Blog personal dengan sidebar, categories, dan newsletter signup.', 'sofir' ),
            'path'        => __DIR__ . '/blog/personal-blog.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/personal-blog.svg',
            'category'    => 'blog',
            'context'     => [ 'page' ],
            'demo_cpt'    => [],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'recipe-blog',
            'title'       => \__( 'Recipe Blog', 'sofir' ),
            'description' => \__( 'Blog resep makanan dengan featured recipes dan category browsing.', 'sofir' ),
            'path'        => __DIR__ . '/blog/recipe-blog.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/recipe-blog.svg',
            'category'    => 'blog',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'recipe' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'travel-blog',
            'title'       => \__( 'Travel Blog', 'sofir' ),
            'description' => \__( 'Blog perjalanan dengan destination guides, map, dan photo gallery.', 'sofir' ),
            'path'        => __DIR__ . '/blog/travel-blog.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/travel-blog.svg',
            'category'    => 'blog',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'guide' ],
            'theme'       => 'block-theme',
        ],
    ],
    'profile'   => [
        [
            'slug'        => 'business-profile',
            'title'       => \__( 'Business Profile', 'sofir' ),
            'description' => \__( 'Profil perusahaan dengan hero, layanan, statistik, dan CTA.', 'sofir' ),
            'path'        => __DIR__ . '/profile/business-profile.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/business-profile.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'service', 'team_member' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'freelancer-portfolio',
            'title'       => \__( 'Freelancer Portfolio', 'sofir' ),
            'description' => \__( 'Portfolio freelancer dengan showcase project, skills, dan contact form.', 'sofir' ),
            'path'        => __DIR__ . '/profile/freelancer-portfolio.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/freelancer-portfolio.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'project' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'creative-agency',
            'title'       => \__( 'Creative Agency', 'sofir' ),
            'description' => \__( 'Website agensi kreatif dengan portfolio, team, dan services.', 'sofir' ),
            'path'        => __DIR__ . '/profile/creative-agency.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/creative-agency.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'project', 'team_member', 'testimonial' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'personal-resume',
            'title'       => \__( 'Personal Resume', 'sofir' ),
            'description' => \__( 'CV online dengan skills, experience, dan portfolio projects.', 'sofir' ),
            'path'        => __DIR__ . '/profile/personal-resume.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/personal-resume.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'experience', 'education', 'project' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'photography-portfolio',
            'title'       => \__( 'Photography Portfolio', 'sofir' ),
            'description' => \__( 'Portfolio fotografer dengan gallery, services, dan pricing.', 'sofir' ),
            'path'        => __DIR__ . '/profile/photography-portfolio.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/photography-portfolio.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'photo', 'testimonial', 'pricing' ],
            'theme'       => 'block-theme',
        ],
    ],
    'ecommerce' => [
        [
            'slug'        => 'product-catalog',
            'title'       => \__( 'Product Catalog', 'sofir' ),
            'description' => \__( 'Katalog produk dengan filter, grid view, dan cart summary.', 'sofir' ),
            'path'        => __DIR__ . '/ecommerce/product-catalog.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/product-catalog.svg',
            'category'    => 'ecommerce',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'product' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'checkout-page',
            'title'       => \__( 'Checkout Page', 'sofir' ),
            'description' => \__( 'Halaman checkout dengan billing form dan order summary.', 'sofir' ),
            'path'        => __DIR__ . '/ecommerce/checkout-page.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/checkout-page.svg',
            'category'    => 'ecommerce',
            'context'     => [ 'page' ],
            'demo_cpt'    => [],
            'theme'       => 'block-theme',
        ],
    ],
    'membership' => [
        [
            'slug'        => 'member-dashboard',
            'title'       => \__( 'Member Dashboard', 'sofir' ),
            'description' => \__( 'Dashboard member dengan stats, activity, dan quick actions.', 'sofir' ),
            'path'        => __DIR__ . '/membership/member-dashboard.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/member-dashboard.svg',
            'category'    => 'membership',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [ 'activity' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'pricing-plans',
            'title'       => \__( 'Pricing Plans', 'sofir' ),
            'description' => \__( 'Halaman pricing dengan comparison table dan testimonials.', 'sofir' ),
            'path'        => __DIR__ . '/membership/pricing-plans.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/pricing-plans.svg',
            'category'    => 'membership',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'pricing', 'testimonial', 'faq' ],
            'theme'       => 'block-theme',
        ],
    ],
    'header' => [
        [
            'slug'        => 'modern-header',
            'title'       => \__( 'Modern Header', 'sofir' ),
            'description' => \__( 'Header modern dengan logo, navigasi horizontal, dan CTA button.', 'sofir' ),
            'path'        => __DIR__ . '/components/modern-header.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/modern-header.svg',
            'category'    => 'header',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
        [
            'slug'        => 'minimal-header',
            'title'       => \__( 'Minimal Header', 'sofir' ),
            'description' => \__( 'Header minimalis dengan tiga kolom: logo, navigasi tengah, dan link login.', 'sofir' ),
            'path'        => __DIR__ . '/components/minimal-header.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/minimal-header.svg',
            'category'    => 'header',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
        [
            'slug'        => 'business-header',
            'title'       => \__( 'Business Header', 'sofir' ),
            'description' => \__( 'Header bisnis profesional dengan top bar info kontak dan navigasi utama.', 'sofir' ),
            'path'        => __DIR__ . '/components/business-header.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/business-header.svg',
            'category'    => 'header',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
        [
            'slug'        => 'centered-header',
            'title'       => \__( 'Centered Header', 'sofir' ),
            'description' => \__( 'Header dengan logo dan title di tengah, navigasi di bawahnya.', 'sofir' ),
            'path'        => __DIR__ . '/components/centered-header.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/centered-header.svg',
            'category'    => 'header',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
    ],
    'footer' => [
        [
            'slug'        => 'multi-column-footer',
            'title'       => \__( 'Multi Column Footer', 'sofir' ),
            'description' => \__( 'Footer dengan 4 kolom: company info, menu links, dan social media.', 'sofir' ),
            'path'        => __DIR__ . '/components/multi-column-footer.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/multi-column-footer.svg',
            'category'    => 'footer',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
        [
            'slug'        => 'simple-footer',
            'title'       => \__( 'Simple Footer', 'sofir' ),
            'description' => \__( 'Footer sederhana tiga kolom: copyright, navigasi, dan social links.', 'sofir' ),
            'path'        => __DIR__ . '/components/simple-footer.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/simple-footer.svg',
            'category'    => 'footer',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
        [
            'slug'        => 'business-footer',
            'title'       => \__( 'Business Footer', 'sofir' ),
            'description' => \__( 'Footer bisnis dengan company info, newsletter form, dan contact details.', 'sofir' ),
            'path'        => __DIR__ . '/components/business-footer.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/business-footer.svg',
            'category'    => 'footer',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
        [
            'slug'        => 'newsletter-footer',
            'title'       => \__( 'Newsletter Footer', 'sofir' ),
            'description' => \__( 'Footer dengan fokus newsletter signup dan gradient background menarik.', 'sofir' ),
            'path'        => __DIR__ . '/components/newsletter-footer.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/newsletter-footer.svg',
            'category'    => 'footer',
            'context'     => [ 'pattern' ],
            'demo_cpt'    => [],
            'theme'       => 'any',
        ],
    ],
];
