<?php
return [
    'landing'   => [
        [
            'slug'        => 'startup-launch',
            'title'       => \__( 'Startup Launch', 'sofir' ),
            'description' => \__( 'Hero besar dengan CTA, daftar fitur, testimoni, dan pricing table.', 'sofir' ),
            'path'        => __DIR__ . '/landing/startup-launch.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/startup-launch.svg',
            'category'    => 'landing',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [ 'testimonial', 'pricing' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'agency-spotlight',
            'title'       => \__( 'Agency Spotlight', 'sofir' ),
            'description' => \__( 'Layout elegan untuk agensi dengan layanan, proses kerja, dan form kontak.', 'sofir' ),
            'path'        => __DIR__ . '/landing/agency-spotlight.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/agency-spotlight.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'service' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'restaurant-menu',
            'title'       => \__( 'Restaurant Menu', 'sofir' ),
            'description' => \__( 'Tampilan menu restoran dengan gambar makanan, harga, dan booking form.', 'sofir' ),
            'path'        => __DIR__ . '/landing/restaurant-menu.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/restaurant-menu.svg',
            'category'    => 'landing',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'menu_item' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'real-estate-property',
            'title'       => \__( 'Real Estate Property', 'sofir' ),
            'description' => \__( 'Landing page properti dengan gallery, spesifikasi, dan contact agent.', 'sofir' ),
            'path'        => __DIR__ . '/landing/real-estate-property.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/real-estate-property.svg',
            'category'    => 'landing',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [ 'property' ],
            'theme'       => 'block-theme',
        ],
    ],
    'directory' => [
        [
            'slug'        => 'city-directory',
            'title'       => \__( 'City Directory', 'sofir' ),
            'description' => \__( 'Listing grid dengan filter lokasi, rating, dan kategori.', 'sofir' ),
            'path'        => __DIR__ . '/directory/city-directory.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/city-directory.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'directory_listing' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'healthcare-network',
            'title'       => \__( 'Healthcare Network', 'sofir' ),
            'description' => \__( 'Direktori dokter dengan pencarian cepat dan highlight layanan.', 'sofir' ),
            'path'        => __DIR__ . '/directory/healthcare-network.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/healthcare-network.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'doctor', 'service' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'fitness-studio-directory',
            'title'       => \__( 'Fitness Studio Directory', 'sofir' ),
            'description' => \__( 'Direktori gym dan studio fitness dengan rating, jadwal, dan booking.', 'sofir' ),
            'path'        => __DIR__ . '/directory/fitness-studio-directory.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/fitness-studio-directory.svg',
            'category'    => 'directory',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'fitness_studio' ],
            'theme'       => 'block-theme',
        ],
    ],
    'blog'      => [
        [
            'slug'        => 'modern-magazine',
            'title'       => \__( 'Modern Magazine', 'sofir' ),
            'description' => \__( 'Portal berita dengan layout hero carousel, kategori, dan highlight editorial.', 'sofir' ),
            'path'        => __DIR__ . '/blog/modern-magazine.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/modern-magazine.svg',
            'category'    => 'blog',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'tech-news-portal',
            'title'       => \__( 'Tech News Portal', 'sofir' ),
            'description' => \__( 'Portal berita teknologi dengan trending sidebar dan latest stories grid.', 'sofir' ),
            'path'        => __DIR__ . '/blog/tech-news-portal.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/tech-news-portal.svg',
            'category'    => 'blog',
            'context'     => [ 'page', 'template' ],
            'demo_cpt'    => [],
            'theme'       => 'block-theme',
        ],
    ],
    'profile'   => [
        [
            'slug'        => 'business-profile',
            'title'       => \__( 'Business Profile', 'sofir' ),
            'description' => \__( 'Profil perusahaan dengan hero, layanan, statistik, dan CTA.', 'sofir' ),
            'path'        => __DIR__ . '/profile/business-profile.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/business-profile.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'service', 'team_member' ],
            'theme'       => 'block-theme',
        ],
        [
            'slug'        => 'freelancer-portfolio',
            'title'       => \__( 'Freelancer Portfolio', 'sofir' ),
            'description' => \__( 'Portfolio freelancer dengan showcase project, skills, dan contact form.', 'sofir' ),
            'path'        => __DIR__ . '/profile/freelancer-portfolio.html',
            'preview'     => SOFIR_PLUGIN_URL . 'assets/images/templates/freelancer-portfolio.svg',
            'category'    => 'profile',
            'context'     => [ 'page' ],
            'demo_cpt'    => [ 'project' ],
            'theme'       => 'block-theme',
        ],
    ],
];
